server:
  port: 8093

spring:
  application:
    name: blocker

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          #issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
          issuer-uri: ${keycloak-location}

keycloak-location: http://keycloak:8080/realms/master