apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-ui-service.shortname" . }}
  labels:
    {{- include "front-ui-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http # Match the container port *name* in the deployment
      protocol: TCP
      name: http
  selector:
    {{- include "front-ui-service.selectorLabels" . | nindent 4 }} 