server:
  port: 8092

spring:
  application:
    name: cash
  config:
    import: 'optional:consul:'

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500
      config:
        enabled: true
        format: YAML
        prefix: config
        defaultContext: application
      discovery:
        instance-id: ${spring.application.name}
        preferIpAddress: false   # Использовать IP адрес вместо имени хоста
        health-check-path: /actuator/health
        healthCheckInterval: 15s
        heartbeat:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          issuer-uri: ${issuer-uri}
          #issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
      client:
        provider:
          keycloak:
            # Ниже - адрес сервера авторизации для получения токена
            issuer-uri: ${issuer-uri}
            #issuer-uri: http://localhost:8080/realms/master # Для запуска локально
            #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
        registration:
          cash: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash
            client-secret: 6UMxwxzxhq3YRamkTEGx4MdEMxPL938n
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  retry:
    instances:
      responseFromModule:
        maxRetryAttempts: 2
        waitDuration: 1s

#Настройки ниже - для запуска без Consul
#module-accounts: http://localhost:8090/
#module-notifications: http://localhost:8091/
#module-blocker: http://localhost:8093/

#Настройки ниже - для запуска в Consul, но без использования consul.config
#(при использовании consul.config для настроек ниже нужно создать папку config/application/consul и скопировать весь раскомментированный блок ниже туда
#module-accounts: http://accounts/
#module-notifications: http://notifications/
#module-blocker: http://blocker/
