package ru.ya.enums;

public enum ErrorOperation {
    USER_ALREADY_EXISTS,
    BANK_ACCOUNT_ALREADY_EXISTS,
    BANK_ACCOUNT_IS_NOT_EMPTY,
    NOT_ENOUGH_MONEY,
    NOT_ENOUGH_MONEY_TO_TRANSFER,
    SUSPICIOUS_OPERATION,
    CLIENT_DOES_NOT_HAVE_BANK_ACCOUNT

}