apiVersion: v1
kind: Service
metadata:
#  annotations:
#    kubectl.kubernetes.io/last-applied-configuration: |
#      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/minikube-addons":"registry"},"name":"registry","namespace":"kube-system"},"spec":{"ports":[{"name":"http","port":80,"targetPort":5000},{"name":"https","port":443,"targetPort":443}],"selector":{"actual-registry":"true","kubernetes.io/minikube-addons":"registry"},"type":"ClusterIP"}}
#  creationTimestamp: "2025-07-13T06:12:33Z"
#  labels:
#    addonmanager.kubernetes.io/mode: Reconcile
#    kubernetes.io/minikube-addons: registry
  name: registry-nodeport
  namespace: kube-system
#  resourceVersion: "733"
#  uid: 07d659bc-69db-4d00-9bdd-47e9df43098b
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 50000
    protocol: TCP
    targetPort: 5000
    nodePort: 30050
#  - name: https
#    port: 443
#    protocol: TCP
#    targetPort: 443
  selector:
    actual-registry: "true"
    kubernetes.io/minikube-addons: registry
  sessionAffinity: None
  type: NodePort
