apiVersion: v2
name: my-microservices-app
description: Umbrella chart for 10 microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Subchart for Accounts Service
  - name: accounts-service
    version: "0.1.0"
    repository: "file://./charts/accounts-service" # Local path reference

  # Subchart for Blocker Service
  - name: blocker-service
    version: "0.1.0"
    repository: "file://./charts/blocker-service" # Local path reference

  # Subchart for Cash Service
  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service" # Local path reference

  # Subchart for Exchange Service
  - name: exchange-service
    version: "0.1.0"
    repository: "file://./charts/exchange-service"  # Local path reference

  # Subchart for Exchange generator Service
  - name: exchange-generator-service
    version: "0.1.0"
    repository: "file://./charts/exchange-generator-service"  # Local path reference

  # Subchart for Front UI Service
  - name: front-ui-service
    version: "0.1.0"
    repository: "file://./charts/front-ui-service"  # Local path reference

  # Subchart for Notifications Service
  - name: notifications-service
    version: "0.1.0"
    repository: "file://./charts/notifications-service"  # Local path reference

  # Subchart for Transfer Service
  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service"  # Local path reference

 # Dependency for Accounts DB (PostgreSQL)
  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: accounts-db # Alias to distinguish this instance
    condition: accounts-db.enabled # Allow disabling if needed

  # Dependency for Keycloak
  - name: keycloak
    version: "24.7.4"
    repository: "https://charts.bitnami.com/bitnami"
    # repository: "https://codecentric.github.io/helm-charts"