apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-example.fullname" . }}-import
data:
  {{- range $file := .Values.keycloak.import.configs }}
  {{ $file }}: |
    {{- . | indent 4 }}
  {{- end }} 