server:
  port: 8095

spring:
  application:
    name: exchange

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
        import-check:
          enabled: false
      discovery:
        ip-address: localhost
        #        instance-id: ${spring.application.name}:${random.value}
        instance-id: ${spring.application.name}
        preferIpAddress: true
        #preferIpAddress: false   # Использовать IP адрес вместо имени хоста
        serviceName: ${spring.application.name} # Имя сервиса
        health-check-url: http://localhost:${server.port}/actuator/health
        health-check-path: /actuator/health
        heartbeat:
          enabled: true       # Отключаем Heartbeat (необязательно)

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
      client:
        provider:
          keycloak:
            # Ниже - адрес сервера авторизации для получения токена
            issuer-uri: http://localhost:8080/realms/master # Для запуска локально
            #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
        registration:
          exchange: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${spring.application.name}
            client-secret: WIzc4IZUM0oDrflwiPqfwc8gfMtGhKos
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

module-exchange-generator: http://localhost:8094/
#module-exchange-generator: http://exchange-generator/