server:
  port: 8095

spring:
  application:
    name: exchange

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          #issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
          issuer-uri: ${keycloak-location}
      client:
        provider:
          keycloak:
            # Ниже - адрес сервера авторизации для получения токена
            #issuer-uri: http://localhost:8080/realms/master # Для запуска локально
            #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
            issuer-uri: ${keycloak-location}
        registration:
          exchange: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${spring.application.name}
            client-secret: 2VgTnsgA6i8dGoZPrJi8pk5ePDQK2oAp
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

#Настройки ниже - для запуска без Consul
#module-exchange-generator: http://localhost:8094/

#Настройки ниже - для запуска в Consul, но без использования consul.config
#(при использовании consul.config для настроек ниже нужно создать папку config/application/consul и скопировать весь раскомментированный блок ниже туда
#module-exchange-generator: http://exchange-generator/

#Настройки ниже - для K8s
#module-exchange-generator: http://exchange-generator.myapp.local/

keycloak-location: http://keycloak:8080/realms/master
module-exchange-generator: http://exchange-generator:8094/