server:
  port: 8095

spring:
  application:
    name: exchange
  config:
    import: 'optional:consul:'

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500
      config:
        enabled: true
        format: YAML
        prefix: config
        defaultContext: application
      discovery:
        instance-id: ${spring.application.name}
        preferIpAddress: false   # Использовать IP адрес вместо имени хоста
        health-check-path: /actuator/health
        healthCheckInterval: 15s
        heartbeat:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Ниже - адрес сервера авторизации для получения токена
          issuer-uri: http://localhost:8080/realms/master # Для запуска локально
          #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
      client:
        provider:
          keycloak:
            # Ниже - адрес сервера авторизации для получения токена
            issuer-uri: http://localhost:8080/realms/master # Для запуска локально
            #issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
        registration:
          exchange: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${spring.application.name}
            client-secret: 2VgTnsgA6i8dGoZPrJi8pk5ePDQK2oAp
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

#Настройки ниже - для запуска без Consul
#module-exchange-generator: http://localhost:8094/

#Настройки ниже - для запуска в Consul, но без использования consul.config
#(при использовании consul.config для настроек ниже нужно создать папку config/application/consul и скопировать весь раскомментированный блок ниже туда
#module-exchange-generator: http://exchange-generator/